site_name: Cocotst Docs
site_url: https://cocotst.linota.cn
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/coconut-google.png
  icon:
      repo: fontawesome/brands/git-alt
      logo: material/file-document-multiple-outline
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 黑暗模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 明亮模式

copyright: 滇ICP备2024034334号 | Copyright &copy; 2024 Linota. 
repo_url: https://github.com/Linota/Cocotst
repo_name: Linota/Cocotst
extra:
  social:
    - icon: scale-balanced-solid
      link: https://beian.miit.gov.cn/
      name: 滇ICP备2024034334号
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref.py
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/zh-cn/3/objects.inv
            - https://docs.aiohttp.org/en/stable/objects.inv
          selection:
            docstring_style: google
          rendering:
            show_submodules: false
            show_signature_annotations: yes
            separate_signature: yes
            docstring_section_style: list
            line_length: 80

  - literate-nav:
      nav_file: NAV.md

  - section-index